# Generated by Django 4.0.2 on 2022-08-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(unique=True, verbose_name='URL')),
                ('short_url', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
