# Generated by Django 4.0.2 on 2022-08-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_url_original_url_alter_url_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.CharField(max_length=1000, verbose_name='URL'),
        ),
    ]
